name: CI Pipeline with Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: owner/trivy-pr-decoration/.github/workflows/trivy-scan.yml@main
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      severity: HIGH,CRITICAL
      ignore-unfixed: true
